### ISSUE TITLE
Beginner question about using python-ffmpeg-downloader library in python

### ISSUE THREAD

**Issue by LuminairPrime** [python-ffmpegio/python-ffmpeg-downloader#1]
Greetings! Sorry about asking a question in the issues section. The good news is that your app works great! :)

I'm learning python and I'm wondering it there's a way to utilize your code by importing and running it in my script, rather than just straight copying and hacking at your code. For example, I want to install and update ffmpeg in the root directory of my script. Is there a way to just run your first function at this directory and make it spit out the ffmpeg? Or do I need to basically copy your init file and redo it for my use? 

Thanks for the help! :)

**Comment by tikuma-lsuhsc** [comment]
@LuminairPrime - Sorry for late reply.

What's the use case of needing binaries at the project root folder? 

I may consider adding dst folder option in the future, but it won't happen any time soon. So, feel free to hack it (that's what open-source software is all about). If you wish to use the package as is, you can monkeypatch `get_dir()` function to achieve your goal. Also, if you wish to add your contribution back to the project, please file a PR.

If you want FFmpeg files to be inside your project folder, you may want to consider [`static_ffmpeg`](https://github.com/zackees/static_ffmpeg) instead. `static_ffmpeg` downloads FFmpeg and FFprobe to the `site-package` folder, and with a virtual environment you can house it inside your project.

Kesh

**Comment by LuminairPrime** [comment]
Working out of the root folder just for simplicity right now. 

Thank you for the advice, I'll look at all that! :)
